from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 917)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 921))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Kemalettin/Desktop/anlasekon/Student Register Form/ss.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 211, 35);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.fpersonal = QtWidgets.QFrame(self.centralwidget)
        self.fpersonal.setGeometry(QtCore.QRect(20, 90, 281, 151))
        self.fpersonal.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.fpersonal.setFrameShape(QtWidgets.QFrame.Box)
        self.fpersonal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fpersonal.setLineWidth(2)
        self.fpersonal.setObjectName("fpersonal")
        self.widget = QtWidgets.QWidget(self.fpersonal)
        self.widget.setGeometry(QtCore.QRect(10, 10, 91, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget1 = QtWidgets.QWidget(self.fpersonal)
        self.widget1.setGeometry(QtCore.QRect(110, 10, 151, 111))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.surname = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(10)
        self.surname.setFont(font)
        self.surname.setText("")
        self.surname.setObjectName("surname")
        self.verticalLayout_2.addWidget(self.surname)
        self.tcnum = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(10)
        self.tcnum.setFont(font)
        self.tcnum.setText("")
        self.tcnum.setObjectName("tcnum")
        self.verticalLayout_2.addWidget(self.tcnum)
        self.Gender = QtWidgets.QGroupBox(self.centralwidget)
        self.Gender.setGeometry(QtCore.QRect(20, 300, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Gender.setFont(font)
        self.Gender.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(153, 153, 153);")
        self.Gender.setFlat(False)
        self.Gender.setCheckable(False)
        self.Gender.setObjectName("Gender")
        self.female = QtWidgets.QRadioButton(self.Gender)
        self.female.setGeometry(QtCore.QRect(20, 30, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.female.setFont(font)
        self.female.setObjectName("female")
        self.male = QtWidgets.QRadioButton(self.Gender)
        self.male.setGeometry(QtCore.QRect(20, 60, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.male.setFont(font)
        self.male.setObjectName("male")
        self.fbirth = QtWidgets.QFrame(self.centralwidget)
        self.fbirth.setGeometry(QtCore.QRect(320, 90, 271, 91))
        self.fbirth.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.fbirth.setFrameShape(QtWidgets.QFrame.Box)
        self.fbirth.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fbirth.setLineWidth(2)
        self.fbirth.setObjectName("fbirth")
        self.label_6 = QtWidgets.QLabel(self.fbirth)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.birthPlace = QtWidgets.QComboBox(self.fbirth)
        self.birthPlace.setGeometry(QtCore.QRect(10, 50, 251, 31))
        self.birthPlace.setObjectName("birthPlace")
        self.fdepartment = QtWidgets.QFrame(self.centralwidget)
        self.fdepartment.setGeometry(QtCore.QRect(320, 190, 271, 91))
        self.fdepartment.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.fdepartment.setFrameShape(QtWidgets.QFrame.Box)
        self.fdepartment.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fdepartment.setLineWidth(2)
        self.fdepartment.setObjectName("fdepartment")
        self.label_11 = QtWidgets.QLabel(self.fdepartment)
        self.label_11.setGeometry(QtCore.QRect(70, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.department = QtWidgets.QComboBox(self.fdepartment)
        self.department.setGeometry(QtCore.QRect(10, 50, 251, 31))
        self.department.setObjectName("department")
        self.EducType = QtWidgets.QGroupBox(self.centralwidget)
        self.EducType.setGeometry(QtCore.QRect(320, 300, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.EducType.setFont(font)
        self.EducType.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(153, 153, 153);")
        self.EducType.setFlat(False)
        self.EducType.setCheckable(False)
        self.EducType.setObjectName("EducType")
        self.first = QtWidgets.QRadioButton(self.EducType)
        self.first.setGeometry(QtCore.QRect(20, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.first.setFont(font)
        self.first.setObjectName("first")
        self.second = QtWidgets.QRadioButton(self.EducType)
        self.second.setGeometry(QtCore.QRect(20, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.second.setFont(font)
        self.second.setObjectName("second")
        self.fbirth_2 = QtWidgets.QFrame(self.centralwidget)
        self.fbirth_2.setGeometry(QtCore.QRect(600, 90, 421, 311))
        self.fbirth_2.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.fbirth_2.setFrameShape(QtWidgets.QFrame.Box)
        self.fbirth_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fbirth_2.setLineWidth(2)
        self.fbirth_2.setObjectName("fbirth_2")
        self.label_12 = QtWidgets.QLabel(self.fbirth_2)
        self.label_12.setGeometry(QtCore.QRect(160, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.fbirth_2)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 60, 371, 201))
        self.calendarWidget.setStyleSheet("color: rgb(0, 0, 255);")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 410, 1001, 80))
        self.frame.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(10, 30, 981, 35))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerAdding = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.registerAdding.setFont(font)
        self.registerAdding.setObjectName("registerAdding")
        self.horizontalLayout.addWidget(self.registerAdding)
        self.registerDeleting = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.registerDeleting.setFont(font)
        self.registerDeleting.setObjectName("registerDeleting")
        self.horizontalLayout.addWidget(self.registerDeleting)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 500, 1071, 421))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(112)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.verticalHeader().setMinimumSectionSize(26)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ÖĞRENCİ KAYIT FORMU"))
        self.label_3.setText(_translate("MainWindow", "Name: "))
        self.label_4.setText(_translate("MainWindow", "Surname: "))
        self.label_5.setText(_translate("MainWindow", "TcNum: "))
        self.Gender.setTitle(_translate("MainWindow", "Cinsiyet"))
        self.female.setText(_translate("MainWindow", "Kadın"))
        self.male.setText(_translate("MainWindow", "Erkek"))
        self.label_6.setText(_translate("MainWindow", "Doğum Yeri"))
        self.label_11.setText(_translate("MainWindow", "Bölüm"))
        self.EducType.setTitle(_translate("MainWindow", "Eğitim Türü"))
        self.first.setText(_translate("MainWindow", "Örgün Öğretim"))
        self.second.setText(_translate("MainWindow", "İkinci Öğretim"))
        self.label_12.setText(_translate("MainWindow", "Doğum Tarihi"))
        self.registerAdding.setText(_translate("MainWindow", "Kayıt Ekle"))
        self.registerDeleting.setText(_translate("MainWindow", "Kayıt Sil"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TcNo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cinsiyet"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Doğum Yeri"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Doğum Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bölüm"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Eğitim Türü"))
